### ISSUE TITLE
help, what's wrong?

### ISSUE THREAD

**Issue by Z-spec** [p4kl0nc4t/Spammer-Grab#13]
![IMG_20200110_030426](https://user-images.githubusercontent.com/58121275/72114869-060de780-3356-11ea-9eb7-74520e869240.jpg)

**Comment by Qu1s** [comment]
You must install module "Click"

`pip install click`

**Comment by ddumpel** [comment]
I tryed `pip install click` too, but it didn't work.. then a I tryed `python3 -m pip install click` and it was done correctly...
