### ISSUE TITLE
TraceBack issue

### ISSUE THREAD

**Issue by shijima1998** [p4kl0nc4t/Spammer-Grab#14]
![Screenshot_20200118-034701_Termux](https://user-images.githubusercontent.com/59771406/72657513-8e6b3880-39a5-11ea-863a-e8302d71c477.jpg)
how can I fix it pls

**Comment by HarleyWildman** [comment]
I'm having the same issue when trying to run spammer.py in termux.

**Comment by p4kl0nc4t** [comment]
https://github.com/p4kl0nc4t/Spammer-Grab/issues/6
