### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by TheNik120** [p4kl0nc4t/Spammer-Grab#16]
![Screenshot_2020-04-09-20-51-06-587_com termux](https://user-images.githubusercontent.com/63420114/78925990-0036b800-7aa5-11ea-81f9-6b236c8b642d.jpg)

**Comment by MrHallows** [comment]
@TheNik120 As stated in the README file:
> You need at least Python 3.7 to run this new Spammer-Grab.
So, instead run `python spammer.py -dl 10 -cc 1 4445556666` where `10` is the delay time, `1` is the country code for your country, and `4445556666` is the target phone number.
