### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KyPyMi** [p4kl0nc4t/Spammer-Grab#2]
Hello, I got an unpleasant problem.  Is there any way to solve it?
![2019_09_09_18 38 13](https://user-images.githubusercontent.com/55063333/64545589-ae248d00-d331-11e9-9754-623940178527.jpg)

**Comment by mitya12342** [comment]
Just remove the -cc option and prepend 7 to number 
Убери кантрикод, и добавь семерку к номеру без плюса

**Comment by p4kl0nc4t** [comment]
-cc option was meant for the country code of a country. It should look like "US" (United States) or "IN" (India).
