### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SAvz310** [p4kl0nc4t/Spammer-Grab#7]
![Screenshot_20191105-144639_Termux](https://user-images.githubusercontent.com/57397773/68205606-ca644380-ffdb-11e9-9960-70384e60bce9.jpg)

**Comment by haxersworld** [comment]
I have encountered same error this use to work flawlessly what happened?? Ty

**Comment by p4kl0nc4t** [comment]
The image showed that you are using an old version of the project. Please clone the latest one. Also, you have to use at least Python 3.6 in order to make it work.
