### ISSUE TITLE
Error/issue

### ISSUE THREAD

**Issue by Betatank** [p4kl0nc4t/Spammer-Grab#8]
![-Dn7E_fgbYY](https://user-images.githubusercontent.com/57450912/68312329-f3600380-00c3-11ea-95a3-229599ab4a02.jpg)

**Comment by VickyBG** [comment]
I have this problem too :/

**Comment by p4kl0nc4t** [comment]
https://github.com/p4kl0nc4t/Spammer-Grab/issues/6
